# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "37956fc732c6c0020997cf4bd1e6ef03"
name = "Blixt Delivery"
handle = "blixt-delivery-1"
application_url = "https://assembly-conditional-grades-sa.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = [
  "https://assembly-conditional-grades-sa.trycloudflare.com/auth/callback",
  "https://assembly-conditional-grades-sa.trycloudflare.com/auth/shopify/callback",
  "https://assembly-conditional-grades-sa.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
